sudo: required
dist: xenial
group: edge
language: python
services:
  - docker

env:
  matrix:
    - DIST=centos-7  PYTHON_VERSION=2
    - DIST=fedora-29 PYTHON_VERSION=2

before_install:
  - docker pull ovirtorg/imageio-test-$DIST

script:
  - |
    docker run \
    --env PYTHON_VERSION=$PYTHON_VERSION \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/src:Z \
    ovirtorg/imageio-test-$DIST \
    bash -c "cd /src && travis/test.sh"
