dist: xenial
group: edge
language: python
os: linux
services:
  - docker

jobs:
  include:
    - env: DIST=centos-8
    - env: DIST=fedora-30
    - env: DIST=fedora-31

before_install:
  - docker pull ovirtorg/imageio-test-$DIST

script:
  - |
    docker run \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/src:Z \
    ovirtorg/imageio-test-$DIST \
    bash -c "cd /src && travis/test.sh"
