archs:
- x86_64:
    distributions:
    - el7
    - el8
    - fc30
- ppc64le:
    distributions:
    - el7
    - el8

stages:
  - check-patch
  - build-artifacts:
      substages:
      - py2:
          distributions:
          - el7
      - py3:
          distributions:
          - fc30
          - el8

release-branches:
  master:
  - ovirt-master
  ovirt-4.3:
  - ovirt-4.3
  ovirt-4.2:
  - ovirt-4.2
